//Creating model user table
/*
    ID INT NOT NULL PK_USER
    NAME VARCHAR(100) NOT NULL
    USERNAME VARCHAR(100) NOT NULL UK_USERNAME
    EMAIL VARCHAR(100) NOT NULL UK_EMAIL
    PASS VARCHAR(100) NOT NULL
*/

